import Head from "next/head"
import Layout from "../components/Layouts/Layout"

export default function Home() {
  return (
    <Layout pageProps={{ page: "dashboard" }}>
      <Head>
        <title>Dashboard | GYMO</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Dashboard</h1>
    </Layout>
  )
}
